package tools.enums;

import tools.anotations.Description;
import tools.anotations.UpdatePoint;

@Description("Enum of all specialization in game (actual)")
@UpdatePoint("09.19.2023")
public enum Specializations
{
    BLOOD_DEATH_KNIGHT,
    FROST_DEATH_KNIGHT,
    UNHOLY_DEATH_KNIGHT,
    HAVOC_DEMON_HUNTER,
    VENGEANCE_DEMON_HUNTER,
    BALANCE_DRUID,
    FERAL_DRUID,
    GUARDIAN_DRUID,
    RESTORATION_DRUID,
    AUGMENTATION_EVOKER,
    DEVASTATION_EVOKER,
    PRESERVATION_EVOKER,
    BEAST_MASTERY_HUNTER,
    MARKSMAN_HUNTER,
    SURVIVAL_HUNTER,
    ARCANE_MAGE,
    FIRE_MAGE,
    FROST_MAGE,
    BREWMASTER_MONK,
    MISTWEAVER_MONK,
    WINDWALKER_MONK,
    HOLY_PALADIN,
    PROTECTION_PALADIN,
    RETRIBUTION_PALADIN,
    DISCIPLINE_PRIEST,
    HOLY_PRIEST,
    SHADOW_PRIEST,
    ASSASSINATION_ROGUE,
    OUTLAW_ROGUE,
    SUBTLETY_ROGUE,
    ELEMENTAL_SHAMAN,
    ENHANCEMENT_SHAMAN,
    RESTORATION_SHAMAN,
    AFFLICTION_WARLOCK,
    DEMONOLOGY_WARLOCK,
    DESTRUCTION_WARLOCK,
    ARMS_WARRIOR,
    FURY_WARRIOR,
    PROTECTION_WARRIOR
}
